services:
  ros_hambot:
    build: .             # Tells Docker Compose to build the local Dockerfile
    image: hambot:${ROBOT_IMAGE_TAG} # Uses the version from the .env file managed by build.sh
    container_name: hambot
    restart: always
    network_mode: host
    ipc: host
    privileged: true     # Grants container access to GPIO, USB, and Serial ports
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ./src:/workspace/src  # Only mount the source code folder
      - /workspace/build       # Keeps heavy build I/O local to container filesystem
      - /workspace/install     # Keeps heavy install I/O local to container filesystem
      - /workspace/log         # Prevents continuous logging from wearing out host disk
    environment:
      - ROS_DOMAIN_ID=30 
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    working_dir: /workspace
    command: sleep infinity