services:
  ros_hambot:
    build: .             # Tells Docker Compose to build the local Dockerfile
    image: hambot:${ROBOT_IMAGE_TAG} # Uses the version from the .env file managed by build.sh
    container_name: hambot
    restart: always
    network_mode: host
    ipc: host
    privileged: true     # Grants container access to GPIO, USB, and Serial ports
    volumes:
      - /dev:/dev
      - /sys:/sys
      - .:/workspace     # Mounts the whole folder to preserve the colcon build/install cache on the host
    environment:
      - ROS_DOMAIN_ID=30 # Keeps traffic isolated to your robot
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # Switches to the highly stable CycloneDDS middleware
    working_dir: /workspace
    command: sleep infinity